name: Release

on:
  release:
    types: [prereleased]
  push:
    branches:
      - main
      - python
      - v*
      - dev*
    paths:
      - "app.py"
      - "Containerfile"
      - "requirements.txt"
      - "templates/index.html"
      - ".github/workflows/release.yml"

jobs:
  build-ghcr:
    name: Build And Push to ghcr.io
    runs-on: ubuntu:latest
    env:
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ github.token }}
      IMAGE_REGISTRY: ghcr.io
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        
      -  
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}/idevsig/filetas:python

  build-docker:
    name: Build And Push to Docker Hub
    runs-on: ubuntu:latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        
      -  
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64
          push: true
          tags: idevsig/filetas:python